# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatbot.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
# this project is done by REVELLA SUNIL
from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
import pandas as pd
from sys import *
from textblob import TextBlob
import nltk
import re
import math
class Ui_MainWindow4(object):
    s="a"
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 780)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-31, -51, 1771, 921))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 175, 169, 255), stop:1 rgba(255, 255, 255, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(280, 30, 501, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 0));")
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(190, 120, 701, 561))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(190, 690, 621, 41))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(815, 690, 81, 41))
        self.pushButton.setStyleSheet("background-color: rgb(106, 106, 106);\n"
"background-color: rgb(161, 161, 161);\n"
"\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(950, 730, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
# this project is done by REVELLA SUNIL
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        f=open("ques.txt","r")
        self.aa=f.readlines()
        f.close()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "WELCOME TO CHAT BOT"))
        self.pushButton.setText(_translate("MainWindow", "SENT"))
        self.pushButton_2.setText(_translate("MainWindow", "Exit"))
    def seet(self):
        s=self.lineEdit.text()
        l=len(self.aa)
        
        v=s.lower()
        v1=v.capitalize()+'\n' 
        obj=TextBlob(v)
        sen=obj.sentiment.polarity
        if(sen==0):
            s=s+"      (it is a neutral sentense)"
                   
        elif(sen>0):
            se1=str(sen*100)+'%'
      # this project is done by REVELLA SUNIL    
            s=s+"      (it is a positive sentence )"+se1
        elif(sen<0):
            a=abs(sen)
            se1=str(a*100)+'%'
            s=s+"   (it is a negative sentense)"+se1
        for i in range(0,l,2):
            if(v1==self.aa[i]):
               ans=self.aa[i+1].strip()
               self.textEdit.append("me  :"+s)
               self.textEdit.append("bot  :"+ans)
               self.lineEdit.setText("")

               break
        else:
               self.textEdit.append("me  :"+s)
               self.textEdit.append("bot  :"+"i can\'t get you")
               self.lineEdit.setText("")
               
    def exi(self):
        sys.exit()
# this project is done by REVELLA SUNIL
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow4()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.pushButton.clicked.connect(ui.seet)
    ui.pushButton_2.clicked.connect(ui.exi)
    sys.exit(app.exec_())
# this project is done by REVELLA SUNIL
