# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login21.ui'
#
# Created by: REVELLA SUNIL
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# this project is done by REVELLA SUNIL
from PyQt5 import QtCore, QtGui, QtWidgets
from chatbot import *
from pcha import *
import mysql.connector
from sys import *
class Ui_MainWindow22(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1040, 771)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(4, 5, 1041, 771))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("clg.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(300, 70, 461, 501))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 167));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(120, 20, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(80, 110, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 200, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgb(154, 154, 154);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 440, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(0, 0, 0, 0));\n"
"color: rgb(255, 0, 0);")
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton_56 = QtWidgets.QPushButton(self.frame)
        self.pushButton_56.setGeometry(QtCore.QRect(170, 330, 121, 51))
        self.pushButton_56.setStyleSheet("border-radius:20px;\n"
"background:rgb(162, 255, 249);")
        self.pushButton_56.setObjectName("pushButton_56")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(150, 270, 131, 21))
        self.label_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 0));")
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(270, 270, 71, 21))
        self.pushButton.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Login Here"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "     Enter the Username"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "      Enter the Password"))
        self.pushButton_56.setText(_translate("MainWindow", "Login"))
        self.label_5.setText(_translate("MainWindow", "forgotten password "))
        self.pushButton.setText(_translate("MainWindow", "Click here"))
    def chatbot(self):
             s=self.lineEdit.text()
             v=self.lineEdit_3.text()
             self.lineEdit.setText("")
             self.lineEdit_3.setText("")
             if(len(s)==0 or len(v)==0):
                 self.label_4.setText("Please fill all the inputs")
             else:    
              myconn = mysql.connector.connect(host = "localhost", user = "root",password = "",database="chatbot")
              cur=myconn.cursor()
             
              cur.execute('select mail_id from chatbot1')
              names=cur.fetchall()
              myconn.close()
              l=len(names)
              for i in range(0,l):
                 if(names[i][0]==s):
                   myconn = mysql.connector.connect(host = "localhost", user = "root",password = "",database="chatbot")
                   cur=myconn.cursor()
                   sql='select password from chatbot1 where mail_id= %s '
                   val=[(s)]
                   cur.execute(sql,val)
                   res=cur.fetchone()
                   myconn.close()
                   if(res[0]==v):
             
                    self.chatbot=QtWidgets.QMainWindow()
                    self.ui=Ui_MainWindow4()
                    self.ui.setupUi(self.chatbot)
                    self.chatbot.show()
                    self.ui.pushButton.clicked.connect(self.ui.seet)
                    self.ui.pushButton_2.clicked.connect(self.ui.exi)
                    break
                   else:
                    self.label_4.setText(" PASSWORD IS WRONG")
                    break
              else:
                 self.label_4.setText("USERNAME  and password notfound")
    def paschange(self):
        self.pcha=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow21()
        self.ui.setupUi(self.pcha)
        self.pcha.show()
        self.ui.pushButton.clicked.connect(self.ui.pcha)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow22()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.pushButton_56.clicked.connect(ui.chatbot)
    ui.pushButton.clicked.connect(ui.paschange)
    sys.exit(app.exec_())
