# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pcha.ui'
#
# Created by:  REVELLA SUNIL
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# this project is done by REVELLA SUNIL

from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector

class Ui_MainWindow21(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(534, 398)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-81, -121, 631, 541))
        self.frame.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(140, 180, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 0));")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(110, 250, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 0));")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(90, 300, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(0, 0, 0, 0));")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(280, 180, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(149, 149, 149);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 250, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(149, 149, 149);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(280, 310, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgb(149, 149, 149);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(280, 400, 141, 51))
        self.pushButton.setStyleSheet("background-color:rgb(176, 201, 255)")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(140, 360, 421, 31))
        self.label_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.577114 rgba(255, 255, 255, 0), stop:1 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 0, 0);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "First name   :"))
        self.label_2.setText(_translate("MainWindow", "Mail Id      :"))
        self.label_3.setText(_translate("MainWindow", "confirm new password :  "))
        self.pushButton.setText(_translate("MainWindow", "change"))
    def pcha(self):
           
        ss=self.lineEdit.text()
        tt=self.lineEdit_2.text()
        uu=self.lineEdit_3.text()
        if(len(ss)==0 or len(tt)==0 or len(uu)==0):
            self.label_4.setText("fill all the inputs")
            
        else:
            myconn = mysql.connector.connect(host = "localhost", user = "root",password = "",database="chatbot")
            cur=myconn.cursor()
            
            cur.execute('select firstname,mail_id  from chatbot1 ')
            fmail=cur.fetchall()
            myconn.close()
            l=len(fmail)
            
            for i in range (0,l):
              if( fmail[i][0]==ss and fmail[i][1]==tt):
                    myconn = mysql.connector.connect(host = "localhost", user = "root",password = "",database="chatbot")
                    cur=myconn.cursor()
                    sql="update chatbot1 set password=%s where firstname=%s and mail_id=%s"
                    val=(uu,ss,tt)
                    cur.execute(sql,val)
                    myconn.commit()
                    myconn.close()
                    self.label_4.setText("Password updated")
                    break
            else:
                self.label_4.setText("first name and mail not matches")
                    
        
        self.lineEdit.setText("")
        self.lineEdit_2.setText("")
        self.lineEdit_3.setText("")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow21()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.pushButton.clicked.connect(ui.pcha)
    sys.exit(app.exec_())
# this project is done by REVELLA SUNIL
